services:
  - type: web
    name: sameer-portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myapp:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: BASE_URL
        sync: false
      - key: APP_SECRET
        sync: false
